spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    #driver-class-name: org.postgresql.Driver
    driverClassName:  org.postgresql.Driver


#management:
#  port: 8081

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap:application:instance_id:${spring:application:name}:${spring:application:instance_id:${server:port}}}
  client:
    registryFetchIntervalSeconds: 5
    healthcheck:
      enabled: true