spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    #driver-class-name: org.postgresql.Driver
    driverClassName:  org.postgresql.Driver


management:
  security:
    enabled: true
  context-path: "/admin"


#management:
#  port: 8081
